title:    "Voyager's log"
author:
  name:   'Maokwen'
  email:  'maokwen@gmail.com'
  github: 'https://github.com/MaoKwen'

url:     '/'
rss:     '/feed.xml'

markdown: kramdown
permalink: ':year-:month-:day-:title/'
safe: true

kramdown:
  input: GFM
